Repository andela/strikers-ah-backend, pull requests merged in 2019-05, with the labels that each got.

#54 Ft 164489792 user should follow each other
  controllers/user.js
  middlewares/verifyToken.js
  migrations/20190418190156-create-following.js
  migrations/20190423155532-create-followers.js
  models/followers.js
  models/following.js
  models/user.js
  package.json
  routes/api/profiles.js
  routes/routes.js
  test/user.js
Labels: Requested review, feature

#64 Ft 164489793 user notification settings
  controllers/user.js
  controllers/userNotification.js
  helpers/mailer.js
  helpers/userEvents.js
  migrations/20190403114111-user.js
  migrations/20190424163354-create-notifications.js
  models/notifications.js
  models/user.js
  package.json
  test/article.js
  test/helpers.js
  test/mailer.js
  test/middlewares.js
  test/usernotifications.js
Labels: Requested review, feature, question

#57 Ft 164489793 user reset password notification
  controllers/user.js
  controllers/userNotification.js
  helpers/mailer.js
  helpers/userEvents.js
  models/user.js
  test/user.js
Labels: Requested review, feature

#65 Ft 164489767 login with page html
  .DS_Store
  test/article.js
  view/css/.DS_Store
  view/css/login.css
  view/css/login.css.map
  view/css/login.scss
  view/img/pic/.DS_Store
Labels: Requested review, refactoring

#67 Ft 164489767 request password html css
  view/css/login.css
  view/css/login.css.map
  view/css/login.scss
  view/forgotpassword.html
Labels: Requested review, feature

#39 Feature(article): Delete article
  controllers/article.js
  models/article.js
  models/user.js
  package.json
  routes/api/articles.js
  test/article.js
  test/user.js
Labels: feature

#44 Feature(article): Create article HTML-CSS page
  view/createArticle.html
  view/css/article.css
Labels: refactoring

#71 ft 164489793 rafactor get notifications for a user
  controllers/user.js
  middlewares/verifyToken.js
  migrations/20190424163354-create-notifications.js
  models/notifications.js
  routes/api/profiles.js
  test/user.js
Labels: Requested review, feature, refactoring

#72 Ft 164489792 return user followers
  controllers/user.js
  models/followers.js
  models/following.js
  package.json
  routes/api/profiles.js
  test/user.js
Labels: Requested review, feature, refactoring

#74 ft-164489793 article notifications
  controllers/article.js
  controllers/notifications.js
  controllers/userNotification.js
  helpers/articleEvents.js
  helpers/mailLinkMaker.js
  helpers/mailer.js
  helpers/userEvents.js
  migrations/20190424163354-create-notifications.js
  models/notifications.js
  test/notifications.js
  test/user.js
Labels: Requested review, feature

#86 redirect user to frontend url after authentication
  controllers/user.js
Labels: Requested review, refactoring
