Repository andela/strikers-ah-backend, pull requests merged in 2019-03, with the labels that each got.

#2 #164489776 installing mocha, chai, chai-http
  models/User.js
  package-lock.json
  package.json
Labels: request review

#4 #164808355 Adding and configuring babel
  .babelrc
  package-lock.json
  package.json
Labels: chore, request review

#3 Ch 164489777 integrating coveralls
  .coveralls.yml
  .gitignore
  .nyc_output/6464b5bf-0868-4c69-939c-baa1aa32dcd1.json
  package-lock.json
  package.json
  test/test.js
Labels: chore, request review

#6 #164489771 integrate Travis-ci with readme badge
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
Labels: chore, request review

#8 Ft configure postgresql as db engine 164489772
  .env.sample
  .eslintrc
  .gitignore
  database/config.js
  index.js
  models/User.js
  package-lock.json
  package.json
  routes/api/index.js
  routes/api/users.js
  routes/index.js
  routes/routes.js
  test/database.js
Labels: feature, request review
