Repository andela/strikers-ah-backend, pull requests merged in 2019-04, with the labels that each got.

#10 #164489778 Setup API documentation using swagger
  .prettierrc
  index.js
  package.json
  swagger.yaml
Labels: request review

#17 #165120272 fixing coveralls errors
  .coveralls.yml
  .env
  README.md
  package-lock.json
  package.json
Labels: chore, request review

#23 Feature #64489786 Article model
  models/article.js
Labels: feature, request review

#30 BG-#165378303 fixing routes conflict problem
  index.js
  package.json
  routes/api/articles.js
  routes/api/authentication.js
  routes/routes.js
  test/homeRoute_test.js
Labels: bug, request review

#21 ft #164489783 integrating SendGrid to send email
  controllers/user.js
  helpers/encrypt.js
  helpers/mailLinkMaker.js
  helpers/mailer.js
  migrations/20190410060956-create-resetpassword.js
  models/resetpassword.js
  models/user.js
  package.json
  routes/api/authentication.js
  test/mailer.js
  test/middlewares.js
  test/user.js
Labels: feature, request review
